##############################
# build for local DEVELOPMENT#
##############################

FROM node:16-alpine3.16 As development

ARG NODE_ENV

ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY --chown=node:node . . 

CMD ["npm", "run", "start"]