##############################
# build for local DEVELOPMENT#
##############################

ARG NODE_ENV

FROM node:18-alpine3.15 As development

ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

RUN touch .env.server

RUN npm install -g @nestjs/cli

COPY --chown=node:node . . 

CMD ["npm", "run", "start:dev"]









